### PR TITLE
Added rounded edges to skyline image

### PR DESCRIPTION
**Pull request by ShubhamPatilsd**
Made images round on the events page so they look better:

Rounded image

Very _very_ low priority PR but yeah

### CODE REVIEW

**Review by JamesClick — APPROVED** [review]
Appr tech change, pending stylistic input

**Comment by oohwooh** [comment]
I think this kind of clashes with the only-slightly rounded edges of the InfoBox, maybe just make these rounded edges match that?
One other change that would be nice to have is a fallback image for if there isn't a skyline photo

**Comment by ShubhamPatilsd** [comment]
I'll try to do this later this week

**Comment by ShubhamPatilsd** [comment]
Hey, so I added the border-radius fix (changed it to `border={3}`) and I just used the CodeDay logo as the fallback image. I don't have a Clear setup (with env vars and stuff) on my local machine since I didn't want to go through so much for that little of a stylistic change. I expect it to work but then again let me know if it acts up.

**Review by oohwooh — APPROVED** [review]

**Comment by oohwooh** [comment]
lgtm! Thanks Shubham :)

**Pull request merged**
